Vagrant.require_version ">= 1.5"

Vagrant.configure("2") do |config|

    config.vm.box = "ubuntu/trusty64"
    
    config.ssh.forward_agent = true

    config.vm.define "db" do |db|
        db.vm.provision :shell, path: "ansible/provision.sh", args: ["db.atest.lan", "db"]
        db.vm.network :private_network, ip: "192.168.45.11"
        db.vm.provider :virtualbox do |v|
            v.name = "db.atest.lan"
            v.customize [
                "modifyvm", :id,
                "--name", "db.atest.lan",
                "--memory", 512,
                "--natdnshostresolver1", "on",
                "--cpus", 1,
            ]
            v.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant", "1"]
        end
    end

    config.vm.define "web" do |web|
        web.vm.provision :shell, path: "ansible/provision.sh", args: ["web.atest.lan", "web"]
        web.vm.synced_folder "./src", "/var/www/atest", type: "nfs"
        web.vm.network :private_network, ip: "192.168.45.10"
        web.vm.provider :virtualbox do |v|
            v.name = "web.atest.lan"
            v.customize [
                "modifyvm", :id,
                "--name", "web.atest.lan",
                "--memory", 256,
                "--natdnshostresolver1", "on",
                "--cpus", 1,
            ]
            v.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant", "1"]
        end
    end

    config.vm.define "doi" do |doi|
        doi.vm.box = "digital_ocean"
        doi.ssh.private_key_path = "~/.ssh/id_rsa"
        doi.vm.provider :digital_ocean do |v|
            v.client_id = "stalin1945"
            v.token = "e66999b119b99ab334baa6b6e348ee1ea921fdc41dd9f978f50b680def204466"
            v.image = "ubuntu-14-04-x64"
            v.region = "fra1"
            v.ssh_key_name="Home"
        end
        doi.vm.provision :shell, path: "ansible/provision.sh", args: ["atest.com", "doi"]
    end

    config.vm.synced_folder "./ansible", "/vagrant", type: "nfs",
        owner: "vagrant",
        group: "www-data",
        mount_options: ["dmode=775,fmode=664"]

end
