---

apache_remove_default_vhost: true
apache_vhosts:
  - servername: 'atest.dev'
    serveralias: '192.168.45.10'
    documentroot: '/var/www/html'
apache_mods_disabled: []

php_packages:
  - php7.0
  - php7.0-curl
  - php7.0-cli
  - php7.0-intl
  - php7.0-json
  - php7.0-dev
  - php7.0-mysql
  - php7.0-opcache
  - php-memcached
  - php7.0-mbstring
  - php7.0-mcrypt
  - php7.0-bcmath
php_enable_webserver: false
php_webserver_daemon: "apache2"
php_enable_php_fpm: false
php_enable_apc: false

app_environments: [atest]

mysql_users:
    - { name: 'atest', password: 'atest', priv: 'atest.*:ALL', host: '%' }
mysql_databases:
    - { name: 'atest' }