Vagrant.require_version ">= 1.5"

Vagrant.configure("2") do |config|

    config.vm.provider :virtualbox do |v|
        v.name = "atest.lan"
        v.customize [
            "modifyvm", :id,
            "--name", "atest.lan",
            "--memory", 256,
            "--natdnshostresolver1", "on",
            "--cpus", 1,
        ]
        v.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant", "1"]
    end

    config.vm.box = "ubuntu/trusty64"
    
    config.vm.network :private_network, ip: "192.168.45.10"
    config.vm.network :forwarded_port, guest: 22, host: 2345
    config.ssh.forward_agent = true

    config.vm.provision :shell, path: "ansible/provision.sh", args: ["atest.lan"]

    config.vm.synced_folder "./src", "/var/www/atest", type: "nfs"

    config.vm.synced_folder "./ansible", "/vagrant", type: "nfs",
        owner: "vagrant",
        group: "www-data",
        mount_options: ["dmode=775,fmode=664"]

end
